
# Create a lookup table for country names and their ISO codes
# The goal of this list is to enable to convert any country name into a current ISO3 code
list_ctry2iso <- list(
    "US" = "USA",
    "Afghanistan, Islamic Rep. of" = "AFG",
    "Albania" = "ALB",
    "Algeria" = "DZA",
    "Angola" = "AGO",
    "Argentina" = "ARG",
    "Armenia, Rep. of" = "ARM",
    "Aruba, Kingdom of the Netherlands" = "ABW",
    "Australia" = "AUS",
    "Austria" = "AUT",
    "Azerbaijan, Rep. of" = "AZE",
    "Bahamas, The" = "BHS",
    "Bahamas" = "BHS",
    "The Bahamas" = "BHS",
    "Bahrain, Kingdom of" = "BHR",
    "Bangladesh" = "BGD",
    "Belarus, Rep. of" = "BLR",
    "Belarus" = "BLR",
    "Belgium" = "BEL",
    "Belize" = "BLZ",
    "Benin" = "BEN",
    "Bermuda" = "BMU",
    "Bhutan" = "BTN",
    "Bolivia" = "BOL",
    "Bosnia and Herzegovina" = "BIH",
    "Botswana" = "BWA",
    "Brazil" = "BRA",
    "Brunei Darussalam" = "BRN",
    "Bulgaria" = "BGR",
    "Burkina Faso" = "BFA",
    "Burundi" = "BDI",
    "Cabo Verde" = "CPV",
    "Cambodia" = "KHM",
    "Cameroon" = "CMR",
    "Canada" = "CAN",
    "Chile" = "CHL",
    "China, P.R.: Mainland" = "CHN",
    "Mainland China" = "CHN",
    "China" = "CHN",
    "China, P.R.: Hong Kong" = "HKG",
    "Hong Kong" = "HKG",
    "China, P.R.: Macao" = "MAC",
    "China, P.R.: Macau" = "MAC",
    "Macao" = "MAC",
    "Macau" = "MAC",
    "Colombia" = "COL",
    "Comoros" = "COM",
    "Congo, Rep. of" = "COG",
    "Congo, Dem. Rep. of the" = "COD",
    "Costa Rica" = "CRI",
    "Côte d'Ivoire" = "CIV",
    "Croatia, Rep. of" = "HRV",
    "Rep. of Croatia" = "HRV",
    "Croatia" = "HRV",
    "Curaçao, Kingdom of the Netherlands" = "CUW",
    "Cyprus" = "CYP",
    "Czech Rep." = "CZE",
    "Denmark" = "DNK",
    "Djibouti" = "DJI",
    "Dominican Rep." = "DOM",
    "Ecuador" = "ECU",
    "Egypt, Arab Rep. of" = "EGY",
    "Arab Rep. of Egypt" = "EGY",
    "Egypt" = "EGY",
    "El Salvador" = "SLV",
    "Equatorial Guinea" = "GNQ",
    "Eritrea, The State of" = "ERI",
    "The State of Eritrea" = "ERI",
    "Eritrea" = "ERI",
    "Estonia, Rep. of" = "EST",
    "Rep. of Estonia" = "EST",
    "Estonia" = "EST",
    "Eswatini, Kingdom of" = "SWZ",
    "Ethiopia, The Federal Dem. Rep. of" = "ETH",
    "The Federal Dem. Rep. of Ethiopia" = "ETH",
    "Ethiopia" = "ETH",
    "Euro Area" = "EMU",
    "Fiji, Rep. of" = "FJI",
    "Fiji" = "FJI",
    "Finland" = "FIN",
    "France" = "FRA",
    "Gabon" = "GAB",
    "Gambia, The" = "GMB",
    "Gambia" = "GMB",
    "Georgia" = "GEO",
    "Germany" = "DEU",
    "Ghana" = "GHA",
    "Greece" = "GRC",
    "Guatemala" = "GTM",
    "Guinea" = "GIN",
    "Guinea-Bissau" = "GNB",
    "Guyana" = "GUY",
    "Haiti" = "HTI",
    "Honduras" = "HND",
    "Hungary" = "HUN",
    "Iceland" = "ISL",
    "India" = "IND",
    "Indonesia" = "IDN",
    "Iraq" = "IRQ",
    "Ireland" = "IRL",
    "Israel" = "ISR",
    "Italy" = "ITA",
    "Jamaica" = "JAM",
    "Japan" = "JPN",
    "Jordan" = "JOR",
    "Kazakhstan, Rep. of" = "KAZ",
    "Rep. of Kazakhstan" = "KAZ",
    "Kazakhstan" = "KAZ",
    "Kenya" = "KEN",
    "Kiribati" = "KIR",
    "Korea, Rep. of" = "KOR",
    "South Korea" = "KOR",
    "Kosovo, Rep. of" = "XKX",
    "Kosovo" = "XKX",
    "Kuwait" = "KWT",
    "Kyrgyz Rep." = "KGZ",
    "Lao People's Dem. Rep." = "LAO",
    "Latvia" = "LVA",
    "Lebanon" = "LBN",
    "Lesotho, Kingdom of" = "LSO",
    "Kingdom of Lesotho" = "LSO",
    "Lesotho" = "LSO",
    "Liberia" = "LBR",
    "Libya" = "LBY",
    "Lithuania" = "LTU",
    "Luxembourg" = "LUX",
    "Madagascar, Rep. of" = "MDG",
    "Rep. of Madagascar" = "MDG",
    "Madagascar" = "MDG",
    "Malawi" = "MWI",
    "Malaysia" = "MYS",
    "Maldives" = "MDV",
    "Mali" = "MLI",
    "Malta" = "MLT",
    "Mauritania, Islamic Rep. of" = "MRT",
    "Islamic Rep. of Mauritania" = "MRT",
    "Mauritania" = "MRT",
    "Mauritius" = "MUS",
    "Mexico" = "MEX",
    "Moldova, Rep. of" = "MDA",
    "Mongolia" = "MNG",
    "Montenegro" = "MNE",
    "Morocco" = "MAR",
    "Mozambique, Rep. of" = "MOZ",
    "Mozambique" = "MOZ",
    "Myanmar" = "MMR",
    "Namibia" = "NAM",
    "Nepal" = "NPL",
    "Netherlands, The" = "NLD",
    "Netherlands" = "NLD",
    "New Zealand" = "NZL",
    "Nicaragua" = "NIC",
    "Niger" = "NER",
    "Nigeria" = "NGA",
    "North Macedonia, Republic of" = "MKD",
    "Rep. of North Macedonia, Republic of" = "MKD",
    "North Macedonia" = "MKD",
    "Macedonia" = "MKD",
    "Norway" = "NOR",
    "Oman" = "OMN",
    "Pakistan" = "PAK",
    "Panama" = "PAN",
    "Papua New Guinea" = "PNG",
    "Paraguay" = "PRY",
    "Peru" = "PER",
    "Philippines" = "PHL",
    "Poland, Rep. of" = "POL",
    "Rep. of Poland" = "POL",
    "Poland" = "POL",
    "Portugal" = "PRT",
    "Qatar" = "QAT",
    "Romania" = "ROU",
    "Russian Federation" = "RUS",
    "Russia" = "RUS",
    "Rwanda" = "RWA",
    "Samoa" = "WSM",
    "São Tomé and Príncipe, Dem. Rep. of" = "STP",
    "Saudi Arabia" = "SAU",
    "Senegal" = "SEN",
    "Serbia, Rep. of" = "SRB",
    "Rep. of Serbia" = "SRB",
    "Serbia" = "SRB",
    "Seychelles" = "SYC",
    "Sierra Leone" = "SLE",
    "Singapore" = "SGP",
    "Sint Maarten, Kingdom of the Netherlands" = "SXM",
    "Slovak Rep." = "SVK",
    "Slovenia, Rep. of" = "SVN",
    "Rep. of Slovenia" = "SVN",
    "Slovenia" = "SVN",
    "Solomon Islands" = "SLB",
    "Somalia" = "SOM",
    "South Africa" = "ZAF",
    "South Sudan, Rep. of" = "SSD",
    "South Sudan" = "SSD",
    "Rep. of South Sudan" = "SSD",
    "Spain" = "ESP",
    "Sri Lanka" = "LKA",
    "Sudan" = "SDN",
    "Suriname" = "SUR",
    "Sweden" = "SWE",
    "Switzerland" = "CHE",
    "Tajikistan, Rep. of" = "TJK",
    "Tanzania, United Rep. of" = "TZA",
    "Tanzania" = "TZA",
    "Thailand" = "THA",
    "Timor-Leste, Dem. Rep. of" = "TLS",
    "Timor-Leste" = "TLS",
    "Togo" = "TGO",
    "Tonga" = "TON",
    "Trinidad and Tobago" = "TTO",
    "Tunisia" = "TUN",
    "Türkiye, Rep. of" = "TUR",
    "Türkiye, Rep of" = "TUR",
    "Türkiye, Rep of" = "TUR",
    "Taiwan" = "TWN",
    "Republic of China" = "TWN",
    "ROC" = "TWN",
    "Taiwan (ROC)" = "TWN",
    "Taiwan Province of China" = "TWN",
    "Uganda" = "UGA",
    "United Kingdom" = "GBR",
    "UK" = "GBR",
    "Ukraine" = "UKR",
    "United Arab Emirates" = "ARE",
    "United Emirates" = "ARE",
    "United States" = "USA",
    "USA" = "USA",
    "Uruguay" = "URY",
    "Uzbekistan, Rep. of" = "UZB",
    "Uzbekistan" = "UZB",
    "Vanuatu" = "VUT",
    "Venezuela, Rep. Bolivariana de" = "VEN",
    "Venezuela" = "VEN",
    "Vietnam" = "VNM",
    "West Bank and Gaza" = "PSE",
    "Yemen, Rep. of" = "YEM",
    "Rep. of Yemen" = "YEM",
    "Yemen" = "YEM",
    "Zambia" = "ZMB",
    "Zimbabwe" = "ZWE",
    "World" = "WLD",
    "Equatorial Guinea, Rep. of" = "GNQ",
    "Grenada" = "GRD",
    "Dominica" = "DMA",
    "Iran, Islamic Rep. of" = "IRN",
    "Antigua and Barbuda" = "ATG",
    "Central African Rep." = "CAF",
    "Montserrat" = "MSR",
    "Anguilla" = "AIA",
    "Barbados" = "BRB",
    "Chad" = "TCD",
    "Comoros, Union of the" = "COM",
    "Curaçao" = "CUW",
    "Sint Maarten" = "SXM",
    "Micronesia, Federated States of" = "FSM",
    "Palau, Rep. of" = "PLW",
    "Cuba" = "CUB",
    "Reunion" = "REU",
    "New Caledonia" = "NCL",
    "Gibraltar" = "GIB",
    "Faroe Islands" = "FRO",
    "Greenland" = "GRL",
    "Nauru, Rep. of" = "NRU",
    "French Polynesia" = "PYF",
    "Guernsey" = "GGY",
    "Jersey" = "JEY",
    "Isle of Man" = "IMN",
    "Andorra, Principality of" = "AND",
    "St. Lucia" = "LCA",
    "St. Vincent and the Grenadines" = "VCT",
    "St. Kitts and Nevis" = "KNA",
    "San Marino, Rep. of" = "SMR",
    "Syrian Arab Rep." = "SYR",
    "Turkmenistan" = "TKM",
    "Czechoslovakia" = "CSK",
    "Anguila" = "AIA",
    "Bosnia & Herzegovina" = "BIH",
    "Cook Islands" = "COK",
    "C“te d?Ivoire" = "CIV",
    "Cura‡ao" = "CUW",
    "Democratic Republic of Congo (Kinshasa)" = "COD",
    "eSwatini (Swaziland)" = "SWZ",
    "The Gambia" = "GMB",
    "Korea (North)" = "PRK",
    "North Korea" = "PRK",
    "Laos" = "LAO",
    "Marshall Islands" = "MHL",
    "Netherlands Antilles" = "ANT",
    "Puerto Rico" = "PRI",
    "Republic of Congo (Brazzaville)" = "COG",
    "S?o Tom‚ and Pr¡ncipe" = "STP",
    "St. Kitts & Nevis" = "KNA",
    "Trinidad & Tobago" = "TTO",
    "Turkey" = "TUR",
    "Tuvalu" = "TUV",
    "USSR/Russia" = "RUS",
    "West Bank & Gaza" = "PSE",
    "Yugoslavia" = "YUG",
    "Republic of Albania" = "ALB",
    "People's Republic of China" = "CHN",
    "PR China" = "CHN",
    "Mainland China" = "CHN",
    "PRC" = "CHN",
    "Republic of Korea" = "KOR",
    "Korea, Republic of" = "KOR",
    "Korea, South" = "KOR",
    "Democratic People's Republic of Korea" = "PRK",
    "Korea, Democratic People's Republic of" = "PRK",
    "Korea, North" = "PRK",
    "DPRK" = "PRK",
    "North Korea" = "PRK",
    "United States of America" = "USA",
    "The United States" = "USA",
    "America" = "USA",
    "Great Britain" = "GBR",
    "Britain" = "GBR",
    "England" = "GBR",
    "United States Virgin Islands" = "VIR",
    "US Virgin Islands" = "VIR",
    "Virgin Islands (US)" = "VIR",
    "British Virgin Islands" = "VGB",
    "Virgin Islands (UK)" = "VGB",
    "Democratic Republic of the Congo" = "COD",
    "DR Congo" = "COD",
    "DRC Congo" = "COD",
    "Congo DRC" = "COD",
    "Congo-Kinshasa" = "COD",
    "DRC" = "COD",
    "Congo (Democratic Republic of)" = "COD",
    "Republic of the Congo" = "COG",
    "Congo-Brazzaville" = "COG",
    "Congo (Republic of)" = "COG",
    "Russian Federation" = "RUS",
    "Russia (Soviet Union)" = "RUS",
    "Soviet Union" = "SUN",
    "Islamic Republic of Iran" = "IRN",
    "Iran" = "IRN",
    "Ivory Coast" = "CIV",
    "The Ivory Coast" = "CIV",
    "Republic of South Africa" = "ZAF",
    "Czechia" = "CZE",
    "Czech Republic" = "CZE",
    "Slovak Republic" = "SVK",
    "Slovakia" = "SVK",
    "Vatican" = "VAT",
    "Holy See" = "VAT",
    "Vatican City State" = "VAT",
    "Vatican City" = "VAT",
    "État de la Cité du Vatican" = "VAT",
    "East Timor" = "TLS",
    "Timor" = "TLS",
    "Democratic Republic of Timor-Leste" = "TLS",
    "Cape Verde" = "CPV",
    "Republic of Cabo Verde" = "CPV",
    "Myanmar (Burma)" = "MMR",
    "Union of Myanmar" = "MMR",
    "Republic of the Union of Myanmar" = "MMR",
    "Kingdom of Thailand" = "THA",
    "Siam" = "THA",
    "Kingdom of Cambodia" = "KHM",
    "Kampuchea" = "KHM",
    "Democratic Kampuchea" = "KHM",
    "Kingdom of Saudi Arabia" = "SAU",
    "State of Palestine" = "PSE",
    "Occupied Palestinian Territory" = "PSE",
    "Palestinian Territories" = "PSE",
    "Palestine, State of" = "PSE",
    "Palestine" = "PSE",
    "Islamic Republic of Pakistan" = "PAK",
    "People's Republic of Bangladesh" = "BGD",
    "Republic of India" = "IND",
    "Bharat" = "IND",
    "Brunei" = "BRN",
    "Nation of Brunei" = "BRN",
    "Sultanate of Brunei" = "BRN",
    "State of Brunei Darussalam" = "BRN",
    "Republic of Singapore" = "SGP",
    "Republic of the Philippines" = "PHL",
    "Sri Lanka (Ceylon)" = "LKA",
    "Democratic Socialist Republic of Sri Lanka" = "LKA",
    "Ceylon" = "LKA",
    "Republic of Iraq" = "IRQ",
    "Republic of Indonesia" = "IDN",
    "Netherlands East Indies" = "IDN",
    "Dutch East Indies" = "IDN",
    "Islamic Republic of Afghanistan" = "AFG",
    "Afghanistan" = "AFG",
    "State of Kuwait" = "KWT",
    "Lao PDR" = "LAO",
    "Laos" = "LAO",
    "Lao People's Democratic Republic" = "LAO",
    "Republic of Belarus" = "BLR",
    "Belorussia" = "BLR",
    "White Russia" = "BLR",
    "Republic of Macedonia" = "MKD",
    "FYROM" = "MKD",
    "Former Yugoslav Republic of Macedonia" = "MKD",
    "Macedonia" = "MKD",
    "South Yemen" = "YMD",
    "Democratic Yemen" = "YMD",
    "North Yemen" = "YMN",
    "Republic of Yemen" = "YEM",
    "Kingdom of Morocco" = "MAR",
    "Republic of Turkey" = "TUR",
    "Turkiye" = "TUR",
    "Türkiye" = "TUR",
    "Republic of Cyprus" = "CYP",
    "Kingdom of Bahrain" = "BHR",
    "Bahrain" = "BHR",
    "State of Qatar" = "QAT",
    "Qatar" = "QAT",
    "United Arab Emirates" = "ARE",
    "UAE" = "ARE",
    "Sultanate of Oman" = "OMN",
    "State of Israel" = "ISR",
    "Lebanon" = "LBN",
    "Lebanese Republic" = "LBN",
    "Republic of Azerbaijan" = "AZE",
    "Azerbaijan" = "AZE",
    "Kingdom of Jordan" = "JOR",
    "State of Libya" = "LBY",
    "Libyan Arab Jamahiriya" = "LBY",
    "Syrian Arab Republic" = "SYR",
    "Syria" = "SYR",
    "Republic of Iraq" = "IRQ",
    "Republic of Kazakhstan" = "KAZ",
    "Republic of Uzbekistan" = "UZB",
    "Republic of Tajikistan" = "TJK",
    "Tajikistan" = "TJK",
    "Kyrgyz Republic" = "KGZ",
    "Kirghizia" = "KGZ",
    "Kyrgyzstan" = "KGZ",
    "Turkmenistan" = "TKM",
    "Republic of Armenia" = "ARM",
    "Armenia" = "ARM",
    "Georgia" = "GEO",
    "Republic of Moldova" = "MDA",
    "Moldavia" = "MDA",
    "Moldova" = "MDA",
    "Kingdom of Norway" = "NOR",
    "Republic of Finland" = "FIN",
    "Kingdom of Sweden" = "SWE",
    "Republic of Estonia" = "EST",
    "Republic of Latvia" = "LVA",
    "Republic of Lithuania" = "LTU",
    "Commonwealth of Australia" = "AUS",
    "New Zealand Aotearoa" = "NZL",
    "Papua New Guinea" = "PNG",
    "Independent State of Papua New Guinea" = "PNG",
    "Republic of Fiji" = "FJI",
    "Kingdom of Tonga" = "TON",
    "Independent State of Samoa" = "WSM",
    "American Samoa" = "ASM",
    "Western Samoa" = "WSM",
    "Solomon Islands" = "SLB",
    "Republic of Vanuatu" = "VUT",
    "New Hebrides" = "VUT",
    "Republic of Kiribati" = "KIR",
    "Gilbert Islands" = "KIR",
    "Republic of Nauru" = "NRU",
    "Republic of the Marshall Islands" = "MHL",
    "Federated States of Micronesia" = "FSM",
    "Republic of Palau" = "PLW",
    "Republic of Maldives" = "MDV",
    "Sultanate of Maldives" = "MDV",
    "Republic of Mauritius" = "MUS",
    "Republic of Seychelles" = "SYC",
    "Union of the Comoros" = "COM",
    "Federal Republic of Somalia" = "SOM",
    "Somali Republic" = "SOM",
    "Republic of Djibouti" = "DJI",
    "Kingdom of Lesotho" = "LSO",
    "Kingdom of Eswatini" = "SWZ",
    "Eswatini" = "SWZ",
    "Swaziland" = "SWZ",
    "Republic of Botswana" = "BWA",
    "Republic of Zimbabwe" = "ZWE",
    "Southern Rhodesia" = "ZWE",
    "Rhodesia" = "ZWE",
    "Republic of Zambia" = "ZMB",
    "Northern Rhodesia" = "ZMB",
    "Republic of Malawi" = "MWI",
    "Nyasaland" = "MWI",
    "Republic of Mozambique" = "MOZ",
    "Portuguese East Africa" = "MOZ",
    "United Republic of Tanzania" = "TZA",
    "Tanganyika and Zanzibar" = "TZA",
    "Republic of Kenya" = "KEN",
    "British East Africa" = "KEN",
    "Republic of Uganda" = "UGA",
    "Republic of Rwanda" = "RWA",
    "Republic of Burundi" = "BDI",
    "Republic of the Sudan" = "SDN",
    "North Sudan" = "SDN",
    "Republic of South Sudan" = "SSD",
    "Republic of Chad" = "TCD",
    "Central African Republic" = "CAF",
    "Empire of Central Africa" = "CAF",
    "Republic of Cameroon" = "CMR",
    "Republic of Equatorial Guinea" = "GNQ",
    "Spanish Guinea" = "GNQ",
    "Gabonese Republic" = "GAB",
    "Republic of the Congo" = "COG",
    "Middle Congo" = "COG",
    "Republic of Angola" = "AGO",
    "Portuguese West Africa" = "AGO",
    "Channel Islands" = "CHI",
    "Northern Mariana Islands" = "MNP",
    "Serbia and Montenegro" = "SCG",
    "Serbia, Montenegro and Kosovo" = "SPI",
    "Azores" = "AZO",
    "Saint Barthélemy" = "BLM",
    "East Germany" = "DDR",
    "West Germany" = "DFR",
    "Guadeloupe" = "GLP",
    "French Guiana" = "GUF",
    "Martinique" = "MTQ",
    "Mayotte" = "MYT",
    "Saint Helena" = "SHN",
    "Tokelau" = "TKL",
    "Wallis and Futuna" = "WLF",
    "Mariana Islands" = "MNP",
    "Republic of Namibia" = "NAM",
    "South West Africa" = "NAM",
    "German South West Africa" = "NAM"
)


# Create a lookup table for ISO codes and their simplified country names
# The goal of this list is to convert ISO3 codes into simplified country names
list_iso2country <- list(
"AFG" = "Afghanistan",
"ALB" = "Albania",
"DZA" = "Algeria",
"AGO" = "Angola",
"ARG" = "Argentina",
"ARM" = "Armenia",
"ABW" = "Aruba",
"AUS" = "Australia",
"AUT" = "Austria",
"AZE" = "Azerbaijan",
"BHS" = "Bahamas",
"BHR" = "Bahrain",
"BGD" = "Bangladesh",
"BLR" = "Belarus",
"BEL" = "Belgium",
"BLZ" = "Belize",
"BEN" = "Benin",
"BMU" = "Bermuda",
"BTN" = "Bhutan",
"BOL" = "Bolivia",
"BIH" = "Bosnia and Herzegovina",
"BWA" = "Botswana",
"BRA" = "Brazil",
"BRN" = "Brunei",
"BGR" = "Bulgaria",
"BFA" = "Burkina Faso",
"BDI" = "Burundi",
"CPV" = "Cabo Verde",
"KHM" = "Cambodia",
"CMR" = "Cameroon",
"CAN" = "Canada",
"CHL" = "Chile",
"HKG" = "Hong Kong",
"MAC" = "Macau",
"CHN" = "China",
"COK" = "Cook Islands",
"COL" = "Colombia",
"COM" = "Comoros",
"COD" = "Congo (DRC)",
"COG" = "Congo (Rep. of)",
"CRI" = "Costa Rica",
"CIV" = "Côte d'Ivoire",
"HRV" = "Croatia",
"CUW" = "Curaçao",
"CYP" = "Cyprus",
"CZE" = "Czech Republic",
"DNK" = "Denmark",
"DJI" = "Djibouti",
"DOM" = "Dominican Republic",
"ECU" = "Ecuador",
"EGY" = "Egypt",
"SLV" = "El Salvador",
"GNQ" = "Equatorial Guinea",
"ERI" = "Eritrea",
"EST" = "Estonia",
"SWZ" = "Eswatini",
"ETH" = "Ethiopia",
"FJI" = "Fiji",
"FIN" = "Finland",
"FRA" = "France",
"GAB" = "Gabon",
"GMB" = "Gambia",
"GEO" = "Georgia",
"DEU" = "Germany",
"GHA" = "Ghana",
"GRC" = "Greece",
"GTM" = "Guatemala",
"GIN" = "Guinea",
"GNB" = "Guinea-Bissau",
"GUY" = "Guyana",
"HTI" = "Haiti",
"HND" = "Honduras",
"HUN" = "Hungary",
"ISL" = "Iceland",
"IND" = "India",
"IDN" = "Indonesia",
"IRQ" = "Iraq",
"IRL" = "Ireland",
"ISR" = "Israel",
"ITA" = "Italy",
"JAM" = "Jamaica",
"JPN" = "Japan",
"JOR" = "Jordan",
"KAZ" = "Kazakhstan",
"KEN" = "Kenya",
"KIR" = "Kiribati",
"KOR" = "South Korea",
"KWT" = "Kuwait",
"KGZ" = "Kyrgyzstan",
"LAO" = "Laos",
"LVA" = "Latvia",
"LBN" = "Lebanon",
"LSO" = "Lesotho",
"LBR" = "Liberia",
"LBY" = "Libya",
"LTU" = "Lithuania",
"LUX" = "Luxembourg",
"MDG" = "Madagascar",
"MWI" = "Malawi",
"MYS" = "Malaysia",
"MDV" = "Maldives",
"MLI" = "Mali",
"MLT" = "Malta",
"MRT" = "Mauritania",
"MUS" = "Mauritius",
"MEX" = "Mexico",
"MDA" = "Moldova",
"MNG" = "Mongolia",
"MNE" = "Montenegro",
"MAR" = "Morocco",
"MOZ" = "Mozambique",
"MMR" = "Myanmar",
"NAM" = "Namibia",
"NPL" = "Nepal",
"NLD" = "Netherlands",
"NZL" = "New Zealand",
"NIC" = "Nicaragua",
"NER" = "Niger",
"NGA" = "Nigeria",
"MKD" = "North Macedonia",
"NOR" = "Norway",
"OMN" = "Oman",
"PAK" = "Pakistan",
"PAN" = "Panama",
"PNG" = "Papua New Guinea",
"PRY" = "Paraguay",
"PER" = "Peru",
"PHL" = "Philippines",
"POL" = "Poland",
"PRT" = "Portugal",
"QAT" = "Qatar",
"ROU" = "Romania",
"RUS" = "Russia",
"RWA" = "Rwanda",
"WSM" = "Samoa",
"STP" = "São Tomé and Príncipe",
"SAU" = "Saudi Arabia",
"SEN" = "Senegal",
"SRB" = "Serbia",
"SYC" = "Seychelles",
"SLE" = "Sierra Leone",
"SGP" = "Singapore",
"SXM" = "Sint Maarten",
"SVK" = "Slovakia",
"SVN" = "Slovenia",
"SLB" = "Solomon Islands",
"SOM" = "Somalia",
"ZAF" = "South Africa",
"SSD" = "South Sudan",
"ESP" = "Spain",
"LKA" = "Sri Lanka",
"SDN" = "Sudan",
"SUR" = "Suriname",
"SWE" = "Sweden",
"CHE" = "Switzerland",
"TJK" = "Tajikistan",
"TZA" = "Tanzania",
"THA" = "Thailand",
"TLS" = "Timor-Leste",
"TGO" = "Togo",
"TON" = "Tonga",
"TTO" = "Trinidad and Tobago",
"TUN" = "Tunisia",
"TUR" = "Turkey",
"TWN" = "Taiwan",
"UGA" = "Uganda",
"UKR" = "Ukraine",
"ARE" = "United Arab Emirates",
"GBR" = "United Kingdom",
"USA" = "United States",
"URY" = "Uruguay",
"UZB" = "Uzbekistan",
"VUT" = "Vanuatu",
"VEN" = "Venezuela",
"VNM" = "Vietnam",
"PSE" = "Palestine",
"YEM" = "Yemen (Rep. of)",
"ZMB" = "Zambia",
"ZWE" = "Zimbabwe",
"GRD" = "Grenada",
"DMA" = "Dominica",
"IRN" = "Iran",
"ATG" = "Antigua and Barbuda",
"CAF" = "Central African Rep.",
"MSR" = "Montserrat",
"AIA" = "Anguilla",
"BRB" = "Barbados",
"TCD" = "Chad",
"FSM" = "Micronesia",
"PLW" = "Palau",
"CUB" = "Cuba",
"REU" = "Reunion",
"NCL" = "New Caledonia",
"GIB" = "Gibraltar",
"FRO" = "Faroe Islands",
"GRL" = "Greenland",
"NRU" = "Nauru",
"PYF" = "French Polynesia",
"GGY" = "Guernsey",
"JEY" = "Jersey",
"IMN" = "Isle of Man",
"AND" = "Andorra",
"LCA" = "St. Lucia",
"VCT" = "St. Vincent and the Grenadines",
"KNA" = "St. Kitts and Nevis",
"SMR" = "San Marino",
"SYR" = "Syria",
"TKM" = "Turkmenistan",
"ASM" = "American Samoa",
"VGB" = "British Virgin Islands",
"CYM" = "Cayman Islands",
"GUM" = "Guam",
"PRK" = "North Korea",
"LIE" = "Liechtenstein",
"MHL" = "Marshall Islands",
"MCO" = "Monaco",
"MNP" = "Northern Mariana Islands",
"PRI" = "Puerto Rico",
"MAF" = "Saint Martin (French part)",
"TCA" = "Turks and Caicos Islands",
"TUV" = "Tuvalu",
"VIR" = "U.S. Virgin Islands",
"AZO" = "Azores",
"BLM" = "Saint Barthélemy",
"DFR" = "West Germany",
"DDR" = "East Germany",
"GLP" = "Guadeloupe",
"GUF" = "French Guiana",
"MTQ" = "Martinique",
"MYT" = "Mayotte",
"SCG" = "Serbia and Montenegro",
"SHN" = "Saint Helena",
"SPI" = "Serbia, Montenegro and Kosovo",
"TKL" = "Tokelau",
"WLF" = "Wallis and Futuna"
)




# Create a lookup table for old ISO codes and their simplified country names
# The goal of this list is to convert old ISO3 codes into simplified country names
# The goal of this list is to complement list_iso2names by providing additional ISO3 codes not currently in used but still used in some database
list_iso2country_old <- list(
    "ANT" = "Netherlands Antilles", # Was dissolved in 2010 into Curaçao (CUW) and Sint Maarten (SXM)
    "SUN" = "Soviet Union", # Dissolved in 1991 into 15 independent states (ARM, AZE, BLR, EST, GEO, KAZ, KGZ, LTU, LVA, MDA, RUS, TJK, TKM, UKR, UZB)
    "ROM" = "Romania", # Changed to ROU in 2002 (same country, different ISO code)
    "CSK" = "Czechoslovakia", # Dissolved in 1993 into Czech Republic (CZE) and Slovakia (SVK)
    "YUG" = "Yugoslavia", # Gradually dissolved from 1992 to 2006 into multiple states (BIH, HRV, MKD, MNE, SRB, SVN)
    "DHY" = "Dahomey", # Changed to BEN (Benin) in 1977 when country changed its name
    "HVO" = "Upper Volta", # Changed to BFA (Burkina Faso) in 1984 when country changed its name
    "ZAR" = "Zaire", # Changed to COD (Democratic Republic of the Congo) in 1997 when country changed its name
    "SWA" = "Swaziland", # Changed to SWZ (Eswatini) in 2018 when country changed its name
    "BUR" = "Burma", # Changed to MMR (Myanmar) in 1989 when country changed its name
    "YMD" = "Democratic Yemen", # South Yemen, merged with YMN (North Yemen) in 1990 to form Yemen (YEM)
    "YMN" = "North Yemen", # North Yemen, merged with YMD (South Yemen) in 1990 to form Yemen (YEM)
    "DDR" = "East Germany", # Merged with West Germany (DFR) in 1990 to form Germany (DEU)
    "DFR" = "West Germany", # Merged with East Germany (DDR) in 1990 to form Germany (DEU)
    "SCG" = "Serbia and Montenegro", # Dissolved in 2006 into Serbia (SRB) and Montenegro (MNE)
    "TMP" = "East Timor", # Changed to TLS (Timor-Leste) in 2002
    "BUR" = "Burma", # Changed to MMR (Myanmar) in 1989 when country changed its name
    "VDR" = "North Vietnam", # Merged with South Vietnam (VNM) in 1976 to form Vietnam (VNM)
    "RHO" = "Rhodesia", # Changed to ZWE (Zimbabwe) in 1980
    "ATB" = "British Antarctic Territory", # Now part of British Overseas Territory (BAT)
    "BUR" = "Burma", # Changed to MMR (Myanmar) in 1989
    "BYS" = "Byelorussian SSR", # Changed to BLR (Belarus) in 1991
    "CTE" = "Canton and Enderbury Islands", # Became part of Kiribati (KIR)
    "CSX" = "Serbia excluding Kosovo", # Historical code for statistical purposes
    "GEL" = "Gilbert Islands", # Became part of Kiribati (KIR)
    "HVO" = "Upper Volta", # Changed to BFA (Burkina Faso) in 1984
    "JTN" = "Johnston Island", # Now administered by the United States
    "MID" = "Midway Islands", # Now part of the United States Minor Outlying Islands
    "NHB" = "New Hebrides", # Changed to VUT (Vanuatu) in 1980
    "PCZ" = "Panama Canal Zone", # Transferred to Panama (PAN) in 1979
    "PCI" = "Pacific Islands (Trust Territory)", # Divided into FSM, MHL, PLW
    "PUS" = "US Miscellaneous Pacific Islands", # Now various US territories
    "PZA" = "Panama Canal Zone", # Alternative code, transferred to Panama (PAN)
    "SKM" = "Sikkim", # Became part of India (IND) in 1975
    "VNM" = "Vietnam", # Used for South Vietnam before unification
    "WAK" = "Wake Island", # Now part of the United States Minor Outlying Islands
    "YMS" = "Yemen Democratic", # Alternative code for South Yemen
    "FXX" = "Metropolitan France", # Changed to FRA
    "NYE" = "New Yemen", # Unified Yemen (YEM)
    "UIS" = "United States Miscellaneous Islands", # Now various US territories
    "VOL" = "Volta", # Alternative code for Upper Volta, now Burkina Faso (BFA)
    "ARA" = "Arab Republic of Egypt", # Changed to EGY
    "BIS" = "British Indian Ocean Territory", # Changed to IOT
    "KNA" = "Saint Kitts-Nevis-Anguilla", # Split into KNA (Saint Kitts and Nevis) and AIA (Anguilla)
    "NIC" = "New Ireland Canton", # Historical territory
    "PMZ" = "Panama Maritime Zone", # Historical code
    "SVK" = "Czechoslovakia", # Alternative code before split
    "TAA" = "Tanganyika", # Merged with Zanzibar to form Tanzania (TZA)
    "UAR" = "United Arab Republic" # Union of Egypt and Syria (1958-1961)
)


# Create a lookup table for old ISO codes and their simplified country names
# The goal of this list is to convert pseudo-ISO3 codes into simplified country names
# The goal of this list is to complement list_iso2names and list_iso2country by providing additional pseudo-ISO3 codes used in some database
list_iso2country_others <- list(
    "EMU" = "Euro Area",
    "XKX" = "Kosovo",
    "ESH" = "Western Sahara",
    "TWN" = "Taiwan",
    "WLD" = "World",
    "CHI" = "Channel Islands",
    "EAP" = "East Asia & Pacific",
    "ECA" = "Europe & Central Asia",
    "LAC" = "Latin America & Caribbean",
    "MNA" = "Middle East & North Africa",
    "SAS" = "South Asia",
    "SSF" = "Sub-Saharan Africa",
    "HIC" = "High Income Countries",
    "UMC" = "Upper Middle Income Countries",
    "LMC" = "Lower Middle Income Countries",
    "LIC" = "Low Income Countries",
    "NAC" = "North America",
    "SSA" = "Sub-Saharan Africa",
    "CIS" = "Commonwealth of Independent States",
    "INX" = "Stateless",
    "EUU" = "European Union",
    "PSS" = "Pacific Island Small States",
    "CSS" = "Caribbean Small States",
    "OSS" = "Other Small States",
    "SST" = "Small States",
    "OED" = "OECD Members",
    "XXX" = "Not Classified",
    "ZZZ" = "Unknown or unspecified",
    "XKS" = "Kosovo",
    "SCG" = "Serbia and Montenegro",
    "RYU" = "Ryukyu Islands",
    "XAC" = "Africa",
    "XLA" = "Latin America",
    "XOC" = "Oceania",
    "XEU" = "Europe",
    "SUM" = "Sum",
    "MED" = "Median",
    "MEA" = "Mean",
    # "STD" = "Standard Deviation",
    "Q1L" = "First Quartile",
    "Q3L" = "Third Quartile"
)



# Create a lookup table for old ISO codes and their recent equivalent ISO codes
list_iso_old2new <- list(
    "ROM" = "ROU", # Romania
    "DHY" = "BEN", # Benin
    "HVO" = "BFA", # Burkina Faso
    "ZAR" = "COD", # Congo (DRC)
    "SWA" = "SWZ", # Eswatini
    "BUR" = "MMR", # Myanmar
    "YMD" = "YEM", # Yemen
    "YMN" = "YEM", # Yemen
    "ANT" = "CUW", # Curaçao
    "BYS" = "BLR", # Belarus
    "CSK" = "CZE", # Czech Republic
    "SCG" = "SRB", # Serbia
    "TMP" = "TLS", # Timor-Leste
    "VDR" = "VNM", # Vietnam
    "RHO" = "ZWE", # Zimbabwe
    "NYE" = "YEM", # Yemen
    "BUR" = "MMR", # Myanmar
    "VOL" = "BFA", # Burkina Faso
    "UAR" = "EGY", # Egypt
    "DDR" = "DEU", # Germany
    "DFR" = "DEU", # Germany
    "YUG" = "SRB", # Serbia
    "SUN" = "RUS", # Russia
    "SKM" = "IND", # India
    "NHB" = "VUT", # Vanuatu
    "GEL" = "KIR", # Kiribati
    "CTE" = "KIR", # Kiribati
    "PCZ" = "PAN", # Panama
    "PZA" = "PAN", # Panama
    "PCI" = "FSM", # Micronesia
    "BIS" = "IOT", # British Indian Ocean Territory
    "TAA" = "TZA", # Tanzania
    "FXX" = "FRA", # France
    "ARA" = "EGY"  # Egypt
)


# Create an ISO2 to ISO3 lookup
# The goal of this list is to convert ISO2 codes into ISO3 codes and the other way around.
list_iso2_to_iso3 <- c(
"GB" = "GBR", "NZ" = "NZL", "IE" = "IRL", "CN" = "CHN", "DE" = "DEU", "TR" = "TUR",
"CO" = "COL", "SE" = "SWE", "BR" = "BRA", "DK" = "DNK", "IN" = "IND", "AR" = "ARG",
"NO" = "NOR", "AU" = "AUS", "JP" = "JPN", "SA" = "SAU", "AT" = "AUT", "NL" = "NLD",
"HU" = "HUN", "GR" = "GRC", "KR" = "KOR", "IL" = "ISR", "CZ" = "CZE", "MY" = "MYS",
"IT" = "ITA", "CA" = "CAN", "FI" = "FIN", "HK" = "HKG", "SG" = "SGP", "US" = "USA",
"MX" = "MEX", "PL" = "POL", "FR" = "FRA", "TH" = "THA", "ID" = "IDN", "BE" = "BEL",
"CL" = "CHL", "ES" = "ESP", "ZA" = "ZAF", "PT" = "PRT", "LU" = "LUX", "CH" = "CHE",
"RU" = "RUS", "PE" = "PER", "BG" = "BGR", "MA" = "MAR", "LV" = "LVA", "CY" = "CYP",
"AE" = "ARE", "IS" = "ISL", "RS" = "SRB", "LT" = "LTU", "RO" = "ROU", "EE" = "EST",
"SK" = "SVK", "MT" = "MLT", "PH" = "PHL", "HR" = "HRV", "SI" = "SVN", "MK" = "MKD",
"DZ" = "DZA", "KW" = "KWT", "IR" = "IRN", "BN" = "BRN", "LB" = "LBN", "ZM" = "ZMB",
"ME" = "MNE", "BO" = "BOL", "AW" = "ABW", "PG" = "PNG", "BB" = "BRB", "FM" = "FSM",
"SD" = "SDN", "AZ" = "AZE", "OM" = "OMN", "BD" = "BGD", "KZ" = "KAZ", "FJ" = "FJI",
"IQ" = "IRQ", "YE" = "YEM", "CM" = "CMR", "BA" = "BIH", "PA" = "PAN", "LA" = "LAO",
"BS" = "BHS", "SR" = "SUR", "GD" = "GRD", "GQ" = "GNQ", "SS" = "SSD", "GA" = "GAB",
"SM" = "SMR", "ZW" = "ZWE", "SL" = "SLE", "PK" = "PAK", "TD" = "TCD", "NG" = "NGA",
"SY" = "SYR", "GY" = "GUY", "MD" = "MDA", "UZ" = "UZB", "NI" = "NIC", "KM" = "COM",
"SZ" = "SWZ", "DO" = "DOM", "KI" = "KIR", "ST" = "STP", "VC" = "VCT", "LY" = "LBY",
"SV" = "SLV", "UY" = "URY", "TJ" = "TJK", "ET" = "ETH", "MM" = "MMR", "BT" = "BTN",
"TM" = "TKM", "MN" = "MNG", "BW" = "BWA", "WS" = "WSM", "HN" = "HND", "BY" = "BLR",
"AF" = "AFG", "BZ" = "BLZ", "AL" = "ALB", "GW" = "GNB", "GE" = "GEO", "LK" = "LKA",
"TT" = "TTO", "AG" = "ATG", "CG" = "COG", "MU" = "MUS", "ML" = "MLI", "TN" = "TUN",
"SN" = "SEN", "MO" = "MAC", "TO" = "TON", "AO" = "AGO", "MR" = "MRT", "GN" = "GIN",
"UA" = "UKR", "CI" = "CIV", "JO" = "JOR", "PY" = "PRY", "UG" = "UGA", "AM" = "ARM",
"GH" = "GHA", "LR" = "LBR", "TW" = "TWN", "CD" = "COD", "MV" = "MDV", "CV" = "CPV",
"BH" = "BHR", "GM" = "GMB", "LS" = "LSO", "TZ" = "TZA", "CF" = "CAF", "MW" = "MWI",
"JM" = "JAM", "CR" = "CRI", "BI" = "BDI", "KH" = "KHM", "DM" = "DMA", "MG" = "MDG",
"VE" = "VEN", "LC" = "LCA", "GT" = "GTM", "QA" = "QAT", "MS" = "MSR", "MZ" = "MOZ",
"KE" = "KEN", "BJ" = "BEN", "KG" = "KGZ", "NE" = "NER", "DJ" = "DJI", "SB" = "SLB",
"BF" = "BFA", "TG" = "TGO", "NP" = "NPL", "KN" = "KNA", "SC" = "SYC", "KY" = "CYM",
"ER" = "ERI", "VN" = "VNM", "RW" = "RWA", "EG" = "EGY", "HT" = "HTI", "VU" = "VUT",
"AI" = "AIA", "AD" = "AND", "BM" = "BMU", "BT" = "BTN", "CC" = "CCK", "CX" = "CXR",
"ET" = "ETH", "FO" = "FRO", "GF" = "GUF", "GP" = "GLP", "GU" = "GUM", "IO" = "IOT",
"KP" = "PRK", "MF" = "MAF", "MM" = "MMR", "MP" = "MNP", "MQ" = "MTQ", "NC" = "NCL",
"NF" = "NFK", "PM" = "SPM", "PN" = "PCN", "PR" = "PRI", "PS" = "PSE", "RE" = "REU",
"SH" = "SHN", "SJ" = "SJM", "SS" = "SSD", "TC" = "TCA", "TF" = "ATF", "TL" = "TLS",
"UM" = "UMI", "VA" = "VAT", "VI" = "VIR", "WF" = "WLF", "YT" = "MYT" 
)





# List of all the categories used by the package
list_categories <- c("CTR_LDR", "CTR_FOL", "SMP_WLD", "SMP_RLD", "SMP_FOL", "CTR", "SMP", "PERI", 
                # Oil/natural resource -related categories
                "NRS_REN", "HYD_EXP", "HYD_IMP",
                # New economic groups
                "BRICS", "EU", "ASEAN", "NAFTA", "MERCOSUR",
                # Regions
                "AFRICA", "AMERICAS", "ASIA", "EUROPE", "OCEANIA",
                # Subregions
                "NORTH_AFRICA", "EAST_AFRICA", "MIDDLE_AFRICA", "WEST_AFRICA", "SOUTH_AFRICA",
                "NORTH_AMERICA", "CARIBBEAN", "CENTRAL_AMERICA", "SOUTH_AMERICA",
                "EAST_ASIA", "SOUTHEAST_ASIA", "SOUTH_ASIA", "WEST_ASIA", "CENTRAL_ASIA",
                "WESTERN_EUROPE", "EASTERN_EUROPE",
                "AUSTRALIA_NZ", "OTHER_OCEANIA")



category_labels <- list(
    # Regions
    AFRICA = "Africa",
    AMERICAS = "Americas",
    ASIA = "Asia",
    EUROPE = "Europe",
    OCEANIA = "Oceania",
    
    # Subregions
    NORTH_AFRICA = "North Africa",
    EAST_AFRICA = "East Africa",
    MIDDLE_AFRICA = "Middle Africa",
    WEST_AFRICA = "West Africa",
    SOUTH_AFRICA = "South Africa",
    NORTH_AMERICA = "North America",
    CARIBBEAN = "Caribbean",
    CENTRAL_AMERICA = "Central America",
    SOUTH_AMERICA = "South America",
    EAST_ASIA = "East Asia",
    SOUTHEAST_ASIA = "Southeast Asia",
    SOUTH_ASIA = "South Asia",
    WEST_ASIA = "Middle East",
    CENTRAL_ASIA = "Central Asia",
    WESTERN_EUROPE = "Western Europe",
    EASTERN_EUROPE = "Eastern Europe",
    AUSTRALIA_NZ = "Australia & New Zealand",
    OTHER_OCEANIA = "Other Oceania",
    
    # Center-Periphery categories
    CTR = "Center",
    SMP = "Semi-Periphery",
    PERI = "Periphery",

    # Energy categories 
    HYD_EXP = "Hydrocarbon-exporters", 
    HYD_IMP = "Hydrocarbon-importers"
)




# Define all groups in a list
list_base_categories <- list(
    # Center Leader Countries
    CTR_LDR = c("USA", "DEU", "FRA", "GBR", "ITA", "JPN"),

    # Center Follower Countries
    CTR_FOL = c("AUS", "AUT", "BEL", "CAN", "CHE", "DNK", "FIN", "ISL", "LUX", 
                "NLD", "NOR", "NZL", "SWE"),

    # Semi-Periphery World-Leader Countries
    SMP_WLD = c("CHN"),

    # Semi-Periphery Regional-Leader Countries
    SMP_RLD = c("BRA", "IDN", "IND", "MEX", "RUS"),

    # Semi-Periphery Follower Countries
    SMP_FOL = c("AGO", "ALB", "ARE", "ARG", "ARM", "AZE", "BGR", "BHR", "BLR", 
                "BOL", "BWA", "CHL", "COG", "COL", "CRI", "CYP", "CZE", "DJI", 
                "DOM", "DZA", "ECU", "ESP", "EST", "GAB", "GEO", "GNQ", "GRC", 
                "HRV", "HUN", "IRL", "IRN", "IRQ", "ISR", "JAM", "JOR", "KAZ",
                "KGZ", "KWT", "LBN", "LBY", "LTU", "LVA", "MAR", "MDA", 
                "MKD", "MLT", "MNG", "MUS", "MYS", "NIC", "OMN", "PAN", "PER", 
                "PHL", "POL", "PRT", "PRY", "QAT", "ROU", "SAU", "SLV", 
                "SRB", "SVK", "SVN", "THA", "TTO", "TUN", "TUR", "UKR", "URY",
                "UZB", "VEN", "ZAF"),

    # Periphery Countries
    PERI = c("AFG", "BDI", "BEN", "BFA", "BGD", "CAF", "CIV", "CMR", "COD", 
            "EGY", "ETH", "GHA", "GIN", "GMB", "GNB", "GTM", "HND", "HTI", 
            "KEN", "KHM", "LAO", "LBR", "LKA", "LSO", "MDG", "MLI", "MMR", 
            "MOZ", "MRT", "MWI", "NAM", "NER", "NGA", "NPL", "PAK", "RWA",
            "SDN", "SEN", "SLE", "SWZ", "SYR", "TCD", "TGO", "TJK", "TZA", 
            "UGA", "VNM", "YEM", "ZMB", "ZWE"),


    # Economic Groups
    BRICS = c("BRA", "RUS", "IND", "CHN", "ZAF"),

    EU = c("AUT", "BEL", "BGR", "HRV", "CYP", "CZE", "DNK", "EST", "FIN", 
           "FRA", "DEU", "GRC", "HUN", "IRL", "ITA", "LVA", "LTU", "LUX", 
           "MLT", "NLD", "POL", "PRT", "ROU", "SVK", "SVN", "ESP", "SWE"),

    ASEAN = c("BRN", "KHM", "IDN", "LAO", "MYS", "MMR", "PHL", "SGP", "THA", "VNM"),

    NAFTA = c("CAN", "MEX", "USA"),

    MERCOSUR = c("ARG", "BRA", "PRY", "URY"),

    # Subregions from WID classification

    # Africa subregions
    NORTH_AFRICA = c("DZA", "EGY", "LBY", "MAR", "SDN", "TUN", "ESH"),
    EAST_AFRICA = c("BDI", "COM", "DJI", "ERI", "ETH", "KEN", "MDG", "MOZ", 
                    "MUS", "MWI", "RWA", "SYC", "SOM", "TZA", "UGA", "ZMB", "ZWE"),
    MIDDLE_AFRICA = c("AGO", "CAF", "CMR", "COD", "COG", "GAB", "GNQ", "STP", "TCD"),
    WEST_AFRICA = c("BEN", "BFA", "CIV", "CPV", "GHA", "GMB", "GIN", "GNB", 
                    "LBR", "MLI", "MRT", "NER", "NGA", "SEN", "SLE", "TGO"),
    SOUTH_AFRICA = c("BWA", "LSO", "NAM", "SWZ", "ZAF"),

    # Americas subregions
    NORTH_AMERICA = c("CAN", "USA", "GRL", "BMU"),
    CARIBBEAN = c("ATG", "BHS", "BRB", "CUB", "DOM", "GRD", "HTI", "JAM", 
                  "KNA", "LCA", "TTO", "VCT", "ABW", "AIA", "BLM", "CYM", "CUW",
                  "GLP", "MAF", "MSR", "MTQ", "PRI", "SXM", "TCA", "VGB", "VIR"),
    CENTRAL_AMERICA = c("BLZ", "CRI", "GTM", "HND", "MEX", "NIC", "PAN", "SLV"),
    SOUTH_AMERICA = c("ARG", "BOL", "BRA", "CHL", "COL", "ECU", "GUY", "PER", 
                      "PRY", "SUR", "URY", "VEN", "GUF"),

    # Asia subregions
    EAST_ASIA = c("CHN", "HKG", "JPN", "KOR", "MAC", "MNG", "TWN", "PRK"),
    SOUTHEAST_ASIA = c("BRN", "IDN", "KHM", "LAO", "MMR", "MYS", "PHL", "SGP", 
                       "THA", "TLS", "VNM"),
    SOUTH_ASIA = c("AFG", "BGD", "BTN", "IND", "LKA", "MDV", "NPL", "PAK"),
    WEST_ASIA = c("ARE", "ARM", "AZE", "BHR", "CYP", "GEO", "IRN", "IRQ", 
                  "ISR", "JOR", "KWT", "LBN", "OMN", "PSE", "QAT", "SAU", 
                  "SYR", "TUR", "YEM"),
    CENTRAL_ASIA = c("KAZ", "KGZ", "TJK", "TKM", "UZB"),

    # Europe subregions
    WESTERN_EUROPE = c("AUT", "BEL", "CHE", "DEU", "DNK", "ESP", "FIN", "FRA", 
                       "GBR", "GRC", "IRL", "ISL", "ITA", "LUX", "NLD", "NOR", 
                       "PRT", "SWE", "MLT", "AND", "GGY", "GIB", "IMN", "JEY", 
                       "LIE", "MCO", "SMR", "FRO", "VAT"),
    EASTERN_EUROPE = c("ALB", "BGR", "BIH", "BLR", "CZE", "EST", "HRV", "HUN", 
                       "LTU", "LVA", "MDA", "MKD", "MNE", "POL", "ROU", "RUS", 
                       "SRB", "SVK", "SVN", "UKR"),

    # Oceania subregions
    AUSTRALIA_NZ = c("AUS", "NZL"),
    OTHER_OCEANIA = c("FJI", "FSM", "KIR", "MHL", "NCL", "NRU", "PNG", "PYF", 
                      "SLB", "TON", "VUT", "WSM", "ASM", "COK", "GUM", "MNP",
                      "MYT", "NIU", "PCN", "REU", "TKL", "TUV", "WLF"),


    # Natural Ressouce category
    # Countries with High level of natural resource rent
    NRS_REN = c("MOZ", "TGO", "EGY", "SLE", "RUS", "TCD", "ZMB", "MNG", "UGA", 
                "TTO", "MYS", "ETH", "MRT", "UZB", "BDI", "NGA", "GIN", "GNB", 
                "VEN", "KAZ", "SYR", "COD", "LBR", "DZA", "IRN", "ARE", "AZE", 
                "GAB", "YEM", "AGO", "GNQ", "QAT", "COG", "IRQ", "SAU", "OMN", 
                "LBY", "KWT"),
    
    # Hydrocarbon-Exporting Countries
    HYD_EXP = c("DZA", "AGO", "ARE", "AZE", "BHR", "BOL", "BRN", "COL", "ECU", 
                "EGY", "GNQ", "COG", "GAB", "IRQ", "IRN", "KAZ", "KWT", "LBY", 
                "MYS", "NGA", "OMN", "QAT", "RUS", "SAU", "SDN", "SYR", "TTO", 
                "TKM", "VEN"),
    
    # Hydrocarbon-Importing Countries
    HYD_IMP = c("ARG", "BGD", "BRA", "CHL", "CHN", "CUB", "DOM", "ETH", "GTM", 
                "HND", "IND", "JAM", "JOR", "KEN", "LBN", "LKA", "MAR", "MDG", 
                "PAK", "PHL", "PRY", "SEN", "THA", "TUN", "TUR", "URY", "ZAF")



)



# Create the composite categories by combining existing ones
list_composite_categories <- list(
    # World Regions
    AFRICA = c(list_base_categories$NORTH_AFRICA, list_base_categories$EAST_AFRICA,
               list_base_categories$MIDDLE_AFRICA, list_base_categories$WEST_AFRICA,
               list_base_categories$SOUTH_AFRICA),
    
    AMERICAS = c(list_base_categories$NORTH_AMERICA, list_base_categories$CARIBBEAN,
                 list_base_categories$CENTRAL_AMERICA, list_base_categories$SOUTH_AMERICA),
    
    ASIA = c(list_base_categories$EAST_ASIA, list_base_categories$SOUTHEAST_ASIA,
             list_base_categories$SOUTH_ASIA, list_base_categories$WEST_ASIA,
             list_base_categories$CENTRAL_ASIA),
    
    EUROPE = c(list_base_categories$WESTERN_EUROPE, list_base_categories$EASTERN_EUROPE),
    
    OCEANIA = c(list_base_categories$AUSTRALIA_NZ, list_base_categories$OTHER_OCEANIA),
    
    # Economic categories
    CTR = c(list_base_categories$CTR_LDR, list_base_categories$CTR_FOL),
    
    SMP_LDR = c(list_base_categories$SMP_WLD, list_base_categories$SMP_RLD),
    
    SMP = c(list_base_categories$SMP_WLD, list_base_categories$SMP_RLD, list_base_categories$SMP_FOL)
)



# Combine base and composite categories into the final list
list_category2iso <- c(list_base_categories, list_composite_categories)



# Combine all data into a single list
ISO_DATA <- list(
    list_ctry2iso = list_ctry2iso,
    list_categories = list_categories,
    list_category2iso = list_category2iso,
    list_iso2country = list_iso2country,
    list_iso2country_old = list_iso2country_old,
    list_iso2country_others = list_iso2country_others,
    list_iso_old2new = list_iso_old2new,
    list_iso2_to_iso3 = list_iso2_to_iso3,
    category_labels = category_labels
)

# Save the combined data
usethis::use_data(ISO_DATA, overwrite = TRUE)
